// Include the ambient declaration for this untyped package entry without a runtime import.
/// <reference path="./openapi-internals.d.ts" />
import { isSafeNumber } from "lossless-json";
import type { GlobalContext, OpenAPI3 } from "openapi-typescript";
import { astToString } from "openapi-typescript/dist/lib/ts.mjs";
import {
  resolveRef,
  scanDiscriminators,
} from "openapi-typescript/dist/lib/utils.mjs";
import transformSchema from "openapi-typescript/dist/transform/index.mjs";
import { isAlias, isScalar, parseDocument, visit } from "yaml";
import {
  OPENAPI_INPUT_LIMIT,
  OPENAPI_OUTPUT_LIMIT,
  openapiOptionsSchema,
  ProjectConfigError,
} from "./openapi-contract";
export function parseOpenapi(input: string): OpenAPI3 {
  if (
    input.length > OPENAPI_INPUT_LIMIT ||
    new TextEncoder().encode(input).length > OPENAPI_INPUT_LIMIT
  )
    throw new ProjectConfigError("too_large");
  if (/\p{Cs}/u.test(input)) throw new ProjectConfigError("invalid_input");
  const doc = parseDocument(input, { intAsBigInt: true, uniqueKeys: true });
  if (doc.errors.length || doc.warnings.length)
    throw new ProjectConfigError("invalid_input");
  let nodes = 0,
    aliases = 0;
  visit(doc, (_key, node, path) => {
    if (++nodes > 1000000) throw new ProjectConfigError("too_large");
    if (path.length > 128) throw new ProjectConfigError("too_deep");
    if (isAlias(node) && ++aliases > 1000)
      throw new ProjectConfigError("too_large");
    if (
      isScalar(node) &&
      (typeof node.value === "number" || typeof node.value === "bigint")
    ) {
      const value = Number(node.value);
      if (
        !Number.isFinite(value) ||
        (typeof node.value === "bigint"
          ? BigInt(value) !== node.value
          : !isSafeNumber(
              // yaml's text parser assigns source to every composed scalar.
              // biome-ignore lint/style/noNonNullAssertion: validated fixed-width index or lookup invariant
              node.source!.replaceAll("_", ""),
            ))
      )
        throw new ProjectConfigError("precision_loss");
      node.value = value;
    }
  });
  let value: unknown;
  try {
    value = doc.toJS({ maxAliasCount: 100 });
  } catch {
    throw new ProjectConfigError("invalid_input");
  }
  if (!value || typeof value !== "object" || Array.isArray(value))
    throw new ProjectConfigError("invalid_input");
  const root = value as Record<string, unknown>;
  if (typeof root.openapi !== "string" || !/^3\.(0|1)(\.|$)/.test(root.openapi))
    throw new ProjectConfigError("unsupported_version");
  const refs = new Set<string>(),
    seen = new WeakSet<object>();
  function scan(item: unknown, depth: number) {
    if (depth > 128) throw new ProjectConfigError("too_deep");
    if (!item || typeof item !== "object") return;
    if (seen.has(item)) throw new ProjectConfigError("invalid_input");
    seen.add(item);
    if (!Array.isArray(item)) Object.setPrototypeOf(item, null);
    for (const [key, v] of Object.entries(item)) {
      if (key === "$ref" && typeof v === "string" && !v.startsWith("#"))
        refs.add(v);
      scan(v, depth + 1);
    }
    seen.delete(item);
  }
  scan(root, 0);
  if (refs.size)
    throw new ProjectConfigError("external_ref", [...refs].slice(0, 10));
  return root as unknown as OpenAPI3;
}
export function generateOpenapi(input: string, raw: unknown = {}) {
  const parsedOptions = openapiOptionsSchema.safeParse(raw);
  if (!parsedOptions.success) throw new ProjectConfigError("invalid_input");
  const options = parsedOptions.data,
    document = parseOpenapi(input);
  const ctx: Omit<GlobalContext, "redoc"> = {
    ...options,
    alphabetize: false,
    arrayLength: false,
    emptyObjectsUnknown: false,
    enumValues: false,
    conditionalEnums: false,
    dedupeEnums: false,
    rootTypesNoSchemaPrefix: false,
    rootTypesKeepCasing: false,
    injectFooter: [],
    postTransform: undefined,
    transform: undefined,
    transformProperty: undefined,
    readWriteMarkers: false,
    silent: true,
    discriminators: scanDiscriminators(document, { silent: true }),
    resolve: <T>(ref: string) => resolveRef<T>(document, ref, { silent: true }),
  };
  try {
    const output =
      (options.includeHeader
        ? "/** Generated by openapi-typescript. Do not edit directly. */\n\n"
        : "") + astToString(transformSchema(document, ctx));
    if (new TextEncoder().encode(output).length > OPENAPI_OUTPUT_LIMIT)
      throw new ProjectConfigError("too_large");
    return { output, bytes: new TextEncoder().encode(output).length };
  } catch (e) {
    if (e instanceof ProjectConfigError) throw e;
    throw new ProjectConfigError("generation_failed");
  }
}
