const DEFAULT_INPUT = `-----BEGIN CERTIFICATE-----
MIICEDCCAbagAwIBAgIUMUDg1vY9i66hqAjYyI9T9mPH810wCgYIKoZIzj0EAwIw
LzEUMBIGA1UEAwwLZXhhbXBsZS5jb20xFzAVBgNVBAoMDkluQnJvd3NlciBUZXN0
MB4XDTI2MDUxNDA2MDM0OVoXDTI3MDUxNDA2MDM0OVowLzEUMBIGA1UEAwwLZXhh
bXBsZS5jb20xFzAVBgNVBAoMDkluQnJvd3NlciBUZXN0MFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEdcC+CqkJzFHyGKKBKTWRIGuvGDIBWWYlrB4L0CO/KCnPtBfS
FijdjHkcEJ2lBly9dtp1Lt5UzPoYCVknPuMGoKOBrzCBrDAtBgNVHREEJjAkggtl
eGFtcGxlLmNvbYIPd3d3LmV4YW1wbGUuY29thwR/AAABMA4GA1UdDwEB/wQEAwIF
oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAd
BgNVHQ4EFgQUxHad3Qkh5iq5haEeM/lktKqHuxEwHwYDVR0jBBgwFoAUxHad3Qkh
5iq5haEeM/lktKqHuxEwCgYIKoZIzj0EAwIDSAAwRQIhAIPh73vLurPZxocqcgKg
Hn8wSGgj89NJp36vq+O0nrDCAiB5Spr+QyCW4HN/mEbpFh0qcEyTqUvAnDBb8ino
rIPjMg==
-----END CERTIFICATE-----
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdcC+CqkJzFHyGKKBKTWRIGuvGDIB
WWYlrB4L0CO/KCnPtBfSFijdjHkcEJ2lBly9dtp1Lt5UzPoYCVknPuMGoA==
-----END PUBLIC KEY-----`;

const ACCEPTED_CERTIFICATE_FORMATS = ".pem,.crt,.cer,.der,.key,.pub,.txt";

const STORAGE_KEYS = {
  input: "tools:certificate-public-key-parser:input",
} as const;

export { ACCEPTED_CERTIFICATE_FORMATS, DEFAULT_INPUT, STORAGE_KEYS };
