const publicPdfExample =
  "JVBERi0xLjcKJYGBgYEKCjEgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9LaWRzIFsgNCAwIFIgNSAwIFIgXQovQ291bnQgMgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKL1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDEgMCBSCj4+CmVuZG9iagoKNCAwIG9iago8PAovVHlwZSAvUGFnZQovUGFyZW50IDEgMCBSCi9SZXNvdXJjZXMgPDwKPj4KL01lZGlhQm94IFsgMCAwIDIwMCAzMDAgXQo+PgplbmRvYmoKCjUgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAxIDAgUgovUmVzb3VyY2VzIDw8Cj4+Ci9NZWRpYUJveCBbIDAgMCAzMDAgMjAwIF0KPj4KZW5kb2JqCgo2IDAgb2JqCjw8Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9UeXBlIC9PYmpTdG0KL04gMQovRmlyc3QgNAovTGVuZ3RoIDE1OAo+PgpzdHJlYW0KeJzVjzsLwjAUhff8iow65ZBnKyEgTbIJzm7FdnAxUOr/96YpbuLs8HFzc859KQ7uPRPXpUyv+7xwn1POgANgNWEBGSkORE9IykmTHb0Jp3fozylAnUnLDetaTdU3r9nrE0Xy2uqJzau7ln/m1lmp9ZC/9ukDE5cyxXGd+SGeJKRFDwOloMztyMSwzONa/ve4bf9HeX69MAT2BkI1Yp8KZW5kc3RyZWFtCmVuZG9iagoKNyAwIG9iago8PAovU2l6ZSA4Ci9Sb290IDIgMCBSCi9JbmZvIDMgMCBSCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9UeXBlIC9YUmVmCi9MZW5ndGggNDEKL1cgWyAxIDIgMiBdCi9JbmRleCBbIDAgOCBdCj4+CnN0cmVhbQp4nGNgYPj/n5FBgIGBkSGIgYGJgQ3EagER94EEoxWQYLJlYAAAbEkETAplbmRzdHJlYW0KZW5kb2JqCgpzdGFydHhyZWYKNTczCiUlRU9G";
export const automationToolNames = {
  "favicon-assets-generator": "tooltab_generate_favicon_assets",
  "local-font-book": "tooltab_local_font_catalog",
  "radio-timecode": "tooltab_encode_radio_timecode",
  "dns-lookup": "tooltab_dns_lookup",
  "reverse-ip-lookup": "tooltab_reverse_ip_lookup",
  "ip-info-lookup": "tooltab_ip_info_lookup",
  "my-ip-address": "tooltab_my_ip_address",
  "current-network-time": "tooltab_current_network_time",
  "code-screenshot-generator": "tooltab_code_screenshot_generator",
  "color-picker": "tooltab_color_picker",
  "screen-recorder": "tooltab_screen_recording_inspector",
  camera: "tooltab_process_camera_snapshot",
  "audio-recorder": "tooltab_audio_recording_inspector",
  "ascii-art-generator": "tooltab_ascii_art_generator",
  "unit-converter": "tooltab_unit_converter",
  "device-information": "tooltab_device_information",
  "archive-viewer": "tooltab_archive_viewer",
  "ical-event-generator": "tooltab_ical_event_generator",
  "openapi-to-typescript-converter": "tooltab_openapi_to_typescript_converter",
  "gitignore-generator": "tooltab_gitignore_generator",
  "user-agent-parser": "tooltab_user_agent_parser",
  "docker-run-to-compose-converter": "tooltab_docker_run_to_compose_converter",
  timer: "tooltab_timer",
  stopwatch: "tooltab_stopwatch",
  "gif-to-animated-webp-converter": "gif_to_animated_webp_converter",
  "gif-to-apng-converter": "gif_to_apng_converter",
  "barcode-generator": "tooltab_barcode_generator",
  "barcode-reader": "tooltab_barcode_reader",
  "curl-converter": "tooltab_curl_converter",
  "png-optimizer": "png_optimizer",
  "svg-optimizer": "svg_optimizer",
  "pgp-key-generator": "tooltab_pgp_key_generator",
  "qr-code-generator": "tooltab_qr_code_generator",
  "qr-code-reader": "tooltab_qr_code_reader",
  "csr-generator": "tooltab_csr_generator",
  "certificate-public-key-parser": "tooltab_certificate_public_key_parser",
  "image-to-avif-converter": "image_to_avif_converter",
  "image-to-ico": "image_to_ico",
  "ssh-key-generator": "tooltab_ssh_key_generator",
  "ssh-public-key-fingerprint": "tooltab_ssh_public_key_fingerprint",
  "jwt-decoder-verifier": "tooltab_jwt_decoder_verifier",
  "jwt-signer": "tooltab_jwt_signer",
  "jwk-pem-converter": "tooltab_jwk_pem_converter",
  "prettier-code-formatter": "tooltab_prettier_code_formatter",
  "sql-formatter-and-linter": "tooltab_sql_formatter_and_linter",
  "image-to-pdf-converter": "image_to_pdf_converter",
  "remove-pdf-owner-password": "remove_pdf_owner_password",

  "cityhash64-hash-text-or-file": "tooltab_cityhash64_hash_text_or_file",
  "highwayhash-hash-text-or-file": "tooltab_highwayhash_hash_text_or_file",

  "robots-txt-generator": "tooltab_robots_txt_generator",
  "sitemap-xml-generator": "tooltab_sitemap_xml_generator",

  "pdf-info-viewer": "pdf_info_viewer",
  "pdf-text-extractor": "pdf_text_extractor",
  "pdf-to-image-converter": "pdf_to_image_converter",

  "siphash-2-4-hash-text-or-file": "tooltab_siphash_2_4_hash_text_or_file",
  "siphash-128-2-4-hash-text-or-file":
    "tooltab_siphash_128_2_4_hash_text_or_file",

  "ripemd128-hash-text-or-file": "tooltab_ripemd128_hash_text_or_file",
  "ripemd256-hash-text-or-file": "tooltab_ripemd256_hash_text_or_file",
  "ripemd320-hash-text-or-file": "tooltab_ripemd320_hash_text_or_file",

  "pdf-merger": "pdf_merger",
  "pdf-splitter": "pdf_splitter",
  "pdf-page-organizer": "pdf_page_organizer",
  "pdf-page-number-adder": "pdf_page_number_adder",

  "markdown-previewer": "tooltab_markdown_previewer",
  "markdown-to-html-converter": "tooltab_markdown_to_html_converter",
  "html-to-markdown-converter": "tooltab_html_to_markdown_converter",

  "murmurhash3-x86-32-hash-text-or-file":
    "tooltab_murmurhash3_x86_32_hash_text_or_file",
  "murmurhash3-x86-128-hash-text-or-file":
    "tooltab_murmurhash3_x86_128_hash_text_or_file",
  "murmurhash3-x64-128-hash-text-or-file":
    "tooltab_murmurhash3_x64_128_hash_text_or_file",

  "crc-checksum-calculator": "tooltab_crc_checksum_calculator",
  "exif-viewer": "inspect_image_metadata",
  "image-metadata-cleaner": "clean_image_metadata",
  "xxhash-xxh32-hash-text-or-file": "tooltab_xxhash_xxh32_hash_text_or_file",
  "xxhash-xxh64-hash-text-or-file": "tooltab_xxhash_xxh64_hash_text_or_file",
  "xxhash-xxh3-64-hash-text-or-file":
    "tooltab_xxhash_xxh3_64_hash_text_or_file",
  "xxhash-xxh3-128-hash-text-or-file":
    "tooltab_xxhash_xxh3_128_hash_text_or_file",

  "json-diff-path": "tooltab_json_diff_path",
  "json-schema-generator": "tooltab_json_schema_generator",
  "json-schema-validator": "tooltab_json_schema_validator",
  "md4-hash-text-or-file": "tooltab_md4_hash_text_or_file",
  "sm3-hash-text-or-file": "tooltab_sm3_hash_text_or_file",
  "whirlpool-hash-text-or-file": "tooltab_whirlpool_hash_text_or_file",
  "aes-encryptor": "tooltab_aes_encryptor",
  "aes-decryptor": "tooltab_aes_decryptor",
  "email-validator": "tooltab_email_validator",
  "eu-vat-number-validator": "tooltab_eu_vat_number_validator",
  "prc-id-validator": "tooltab_prc_id_validator",
  "ksuid-generator": "tooltab_ksuid_generator",
  "jsonpath-tester": "tooltab_jsonpath_tester",
  "jmespath-tester": "tooltab_jmespath_tester",
  "bip39-mnemonic-generator": "tooltab_bip39_mnemonic_generator",
  "pbkdf2-key-derivation": "tooltab_pbkdf2_key_derivation",
  "scrypt-key-derivation": "tooltab_scrypt_key_derivation",
  "random-password-generator": "tooltab_random_password_generator",
  "password-strength-checker": "tooltab_password_strength_checker",
  "argon2-hash-password": "tooltab_argon2_hash_password",
  "argon2-hash-password-verifier": "tooltab_argon2_hash_password_verifier",

  "bcrypt-hash-password": "tooltab_bcrypt_hash_password",
  "bcrypt-hash-password-verifier": "tooltab_bcrypt_hash_password_verifier",

  "random-number-generator": "tooltab_random_number_generator",
  "http-status-code-lookup": "tooltab_http_status_code_lookup",
  "mime-type-lookup": "tooltab_mime_type_lookup",
  "port-number-lookup": "tooltab_port_number_lookup",
  "cron-expression-parser": "tooltab_cron_expression_parser",
  "cron-expression-generator": "tooltab_cron_expression_generator",
  "unicode-invisible-character-checker":
    "tooltab_unicode_invisible_character_checker",
  "morse-code-converter": "tooltab_morse_code_converter",
  "lorem-ipsum-generator": "tooltab_lorem_ipsum_generator",

  "json-to-xml-converter": "tooltab_json_to_xml_converter",
  "xml-to-json-converter": "tooltab_xml_to_json_converter",
  "file-to-data-uri-converter": "tooltab_file_to_data_uri_converter",
  "data-uri-to-file-converter": "tooltab_data_uri_to_file_converter",

  "html-color-names": "tooltab_html_color_names",
  "time-zone-converter": "tooltab_time_zone_converter",
  "time-diff-calculator": "tooltab_time_diff_calculator",
  "duration-calculator": "tooltab_duration_calculator",
  "business-days-calculator": "tooltab_business_days_calculator",
  "json-to-yaml-converter": "tooltab_json_to_yaml_converter",
  "yaml-to-json-converter": "tooltab_yaml_to_json_converter",
  "json-to-toml-converter": "tooltab_json_to_toml_converter",
  "toml-to-json-converter": "tooltab_toml_to_json_converter",
  "yaml-to-toml-converter": "tooltab_yaml_to_toml_converter",
  "toml-to-yaml-converter": "tooltab_toml_to_yaml_converter",
  "text-diff": "tooltab_text_diff",
  "regex-tester-replacer": "tooltab_regex_tester_replacer",
  "cidr-parser": "tooltab_cidr_parser",
  "ip-cidr-normalizer": "tooltab_ip_cidr_normalizer",
  "ip-range-to-cidr-converter": "tooltab_ip_range_to_cidr_converter",
  "cidrs-merger-excluder": "tooltab_cidrs_merger_excluder",
  "csv-to-json-converter": "tooltab_csv_to_json_converter",
  "json-to-csv-converter": "tooltab_json_to_csv_converter",
  "mac-address-to-ipv6-link-local-address-converter":
    "tooltab_mac_address_to_ipv6_link_local_address_converter",
  "ipv6-address-to-mac-address-converter":
    "tooltab_ipv6_address_to_mac_address_converter",
  "unicode-punycode-converter": "tooltab_unicode_punycode_converter",
  "url-parser-builder": "tooltab_url_parser_builder",
  "hmac-generator": "tooltab_hmac_generator",
  "sri-hash-generator": "tooltab_sri_hash_generator",
  "ulid-generator": "tooltab_ulid_generator",
  "nanoid-generator": "tooltab_nanoid_generator",
  "cuid2-generator": "tooltab_cuid2_generator",
  "isbn-validator": "tooltab_isbn_validator",
  "vin-validator": "tooltab_vin_validator",
  "credit-card-validator": "tooltab_credit_card_validator",
  "list-comparer": "tooltab_list_comparer",
  "slug-generator": "tooltab_slug_generator",
  "chmod-calculator": "tooltab_chmod_calculator",
  "css-box-shadow-generator": "tooltab_css_box_shadow_generator",
  "css-gradient-generator": "tooltab_css_gradient_generator",
  "iban-validator": "tooltab_iban_validator",
  "bic-swift-validator": "tooltab_bic_swift_validator",
  "imei-validator": "tooltab_imei_validator",

  "unix-timestamp-converter": "tooltab_unix_timestamp_converter",
  "color-converter": "tooltab_color_converter",
  "color-contrast-checker": "tooltab_color_contrast_checker",

  "svg-to-image": "tooltab_svg_to_image",
  "placeholder-generator": "tooltab_placeholder_generator",
  "adler32-hash-text-or-file": "tooltab_adler32_hash_text_or_file",
  "md5-hash-text-or-file": "tooltab_md5_hash_text_or_file",
  "ripemd160-hash-text-or-file": "tooltab_ripemd160_hash_text_or_file",

  "html-entity-encoder-decoder": "tooltab_html_entity_encoder_decoder",
  "unicode-escape-unescape": "tooltab_unicode_escape_unescape",
  "rot-cipher": "tooltab_rot_cipher",

  "base58-encoder": "tooltab_base58_encoder",
  "base58-decoder": "tooltab_base58_decoder",
  "base85-encoder": "tooltab_base85_encoder",
  "base85-decoder": "tooltab_base85_decoder",

  "palette-extractor": "tooltab_palette_extractor",
  "number-base-converter": "tooltab_number_base_converter",
  "roman-numeral-converter": "tooltab_roman_numeral_converter",
  "chinese-uppercase-number-converter":
    "tooltab_chinese_uppercase_number_converter",
  "basic-auth-generator": "tooltab_basic_auth_generator",
  "basic-auth-decoder": "tooltab_basic_auth_decoder",
  "cookie-parser": "tooltab_cookie_parser",

  "base16-encoder": "tooltab_base16_encoder",
  "base16-decoder": "tooltab_base16_decoder",
  "base32-encoder": "tooltab_base32_encoder",
  "base32-decoder": "tooltab_base32_decoder",
  "uuid-v1-generator": "tooltab_uuid_v1_generator",
  "uuid-v6-generator": "tooltab_uuid_v6_generator",
  "uuid-v1-v6-converter": "tooltab_uuid_v1_v6_converter",

  "blake2b-hash-text-or-file": "tooltab_blake2b_hash_text_or_file",
  "blake2s-hash-text-or-file": "tooltab_blake2s_hash_text_or_file",
  "blake3-hash-text-or-file": "tooltab_blake3_hash_text_or_file",
  "keccak-hash-text-or-file": "tooltab_keccak_hash_text_or_file",
  "uuid-v3-generator": "tooltab_uuid_v3_generator",
  "uuid-v5-generator": "tooltab_uuid_v5_generator",

  "uuid-validator": "tooltab_uuid_validator",
  "uuid-decoder": "tooltab_uuid_decoder",
  "uuid-base64-hex-decimal-octal-binary-converter":
    "tooltab_uuid_base64_hex_decimal_octal_binary_converter",
  "image-to-webp": "tooltab_image_to_webp",
  "image-resizer": "tooltab_image_resizer",
  "uuid-v7-generator": "tooltab_uuid_v7_generator",
  "sha224-hash-text-or-file": "tooltab_sha224_hash_text_or_file",
  "sha512-224-hash-text-or-file": "tooltab_sha512_224_hash_text_or_file",
  "sha512-256-hash-text-or-file": "tooltab_sha512_256_hash_text_or_file",
  "sha3-224-hash-text-or-file": "tooltab_sha3_224_hash_text_or_file",
  "sha3-256-hash-text-or-file": "tooltab_sha3_256_hash_text_or_file",
  "sha3-384-hash-text-or-file": "tooltab_sha3_384_hash_text_or_file",
  "sha3-512-hash-text-or-file": "tooltab_sha3_512_hash_text_or_file",
  "shake128-hash-text-or-file": "tooltab_shake128_hash_text_or_file",
  "shake256-hash-text-or-file": "tooltab_shake256_hash_text_or_file",

  "sha1-hash-text-or-file": "tooltab_sha1_hash_text_or_file",
  "sha256-hash-text-or-file": "tooltab_sha256_hash_text_or_file",
  "sha384-hash-text-or-file": "tooltab_sha384_hash_text_or_file",
  "sha512-hash-text-or-file": "tooltab_sha512_hash_text_or_file",
  "uuid-v4-generator": "tooltab_uuid_v4_generator",
  "uuid-v4-bulk-generator": "tooltab_uuid_v4_bulk_generator",
  "uuid-nil-generator": "tooltab_uuid_nil_generator",
  "uuid-max-generator": "tooltab_uuid_max_generator",
  "case-converter": "tooltab_case_converter",
  "text-statistics": "tooltab_text_statistics",
  "ipv6-ula-generator": "tooltab_ipv6_ula_generator",
  "json-formatter": "tooltab_json_formatter",
  "base64-encoder-decoder": "tooltab_base64_encoder_decoder",
  "url-component-encoder-decoder": "tooltab_url_component_encoder_decoder",
} as const;
export const automationExamples = {
  "favicon-assets-generator": {
    source:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWNQa/kPAAJ9AaryYZgoAAAAAElFTkSuQmCC",
    sourceMimeType: "image/png",
    name: "ToolTab",
    shortName: "ToolTab",
    description: "Open tools. Local first.",
    startUrl: "/",
    assetPath: "/icons/",
    display: "standalone",
    themeColor: "#0066cc",
    enableDarkThemeColor: true,
    darkThemeColor: "#2997ff",
    backgroundColor: "#ffffff",
    includeMaskable: true,
    desktop: {
      margin: 8,
      addBackground: true,
      backgroundColor: "#ffffff",
      backgroundRadius: 20,
    },
    ios: { margin: 8, backgroundColor: "#ffffff" },
    pwa: {
      margin: 8,
      addBackground: true,
      backgroundColor: "#ffffff",
      backgroundRadius: 20,
      maskableBackgroundColor: "#ffffff",
      maskableMargin: 40,
    },
    preserveSvg: true,
    optimizePng: true,
    delivery: "artifact",
  },
  "local-font-book": {
    fonts: [
      {
        family: "Inter",
        fullName: "Inter Italic",
        postscriptName: "Inter-Italic",
        style: "Italic",
      },
    ],
    query: "Inter",
    style: "italic",
  },
  "radio-timecode": {
    station: "dcf77",
    timestamp: "2026-09-05T12:34:00.000Z",
  },
  "dns-lookup": {
    name: "example.com",
    recordTypes: ["A", "AAAA"],
    resolver: "cloudflare",
    dnssec: true,
    checkingDisabled: false,
  },
  "reverse-ip-lookup": { ip: "8.8.8.8", resolver: "cloudflare" },
  "ip-info-lookup": { target: "example.com", resolver: "cloudflare" },
  "my-ip-address": {},
  "current-network-time": {},
  "code-screenshot-generator": {
    code: "const greeting = 'Hello, ToolTab';\nconsole.log(greeting);",
    language: "typescript",
    renderMode: "highlight",
    theme: "nebula",
    backgroundMode: "preset",
    backgroundPreset: "aurora",
    backgroundColor: "#0066cc",
    windowStyle: "mac",
    lineNumbers: true,
    fontSize: 15,
    lineHeight: 1.5,
    cardPadding: 32,
    framePadding: 48,
    radius: 16,
    shadow: true,
    tabSize: 2,
    format: "svg",
    scale: 1,
    quality: 94,
    delivery: "inline",
    filename: "code-shot",
  },
  "color-picker": {
    input: "#0066CC",
    format: "hex",
    showAlpha: true,
  },
  "screen-recorder": {
    input: "GkXfo3dlYm0=",
    filename: "screen-demo.webm",
    claimedMimeType: "video/webm",
    delivery: "metadata",
  },
  camera: {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWNQa/kPAAJ9AaryYZgoAAAAAElFTkSuQmCC",
    format: "png",
    quality: 92,
    delivery: "inline",
  },
  "audio-recorder": {
    input: "UklGRgQAAABXQVZF",
    filename: "recording.wav",
    claimedMimeType: "audio/wav",
    delivery: "metadata",
  },
  "ascii-art-generator": {
    text: "ToolTab\nship today",
    font: "Standard",
    align: "left",
    width: 100,
    delivery: "inline",
  },
  "unit-converter": {
    category: "speed",
    value: "100",
    from: "kilometerPerHour",
    to: "milePerHour",
    precision: "6",
    locale: "en-US",
  },
  "device-information": {},
  "archive-viewer": {
    filename: "hello.txt.gz",
    action: "list",
    delivery: "inline",
    source: { input: "H4sIAPfHm2oAA8tIzcnJBwCGphA2BQAAAA==" },
  },
  "ical-event-generator": {
    event: {
      summary: "Project catch-up",
      location: "Meeting room",
      url: "https://example.com/meeting",
      notes: "Review progress and plan the next steps.",
      uid: "synthetic-event@tooltab.example",
      allDay: false,
      timeZone: "UTC",
      outputMode: "utc",
      disambiguation: "reject",
      startDate: "2026-09-08",
      startTime: "09:00",
      endDate: "2026-09-08",
      endTime: "09:30",
      frequency: "none",
      interval: 1,
      weekdays: [],
      monthDay: 1,
      month: 1,
      endMode: "never",
      count: 1,
      untilDate: "2026-09-08",
      untilTime: "09:30",
      remindersEnabled: true,
      reminders: [{ amount: 10, unit: "minutes" }],
    },
    nowMs: 1788832800000,
  },
  "openapi-to-typescript-converter": {
    input:
      '{"openapi":"3.1.0","paths":{},"components":{"schemas":{"Example":{"type":"string"}}}}',
  },
  "gitignore-generator": {
    selected: ["Node", "Python"],
    query: "",
    category: "all",
  },
  "user-agent-parser": {
    input:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  },
  "docker-run-to-compose-converter": {
    input: "docker run --name public-example -p 8080:80 nginx:alpine",
  },
  timer: { action: "start", nowMs: 1000 },
  stopwatch: { action: "start", nowMs: 1000 },
  "gif-to-animated-webp-converter": {
    source: {
      input:
        "R0lGODlhAwADAIAAAExpcf8AACH/C05FVFNDQVBFMi4wAwECAAAh+QQFAgAAACwAAAAAAwADAAACA4x/BQAh+QQFCgAAACwAAAAAAwADAIBMaXEA/wACA4x/BQAh+QQFGQAAACwAAAAAAwADAIBMaXEAAP8CA4x/BQA7",
    },
    delivery: "inline",
  },
  "gif-to-apng-converter": {
    source: {
      input:
        "R0lGODlhAwADAIAAAExpcf8AACH/C05FVFNDQVBFMi4wAwECAAAh+QQFAgAAACwAAAAAAwADAAACA4x/BQAh+QQFCgAAACwAAAAAAwADAIBMaXEA/wACA4x/BQAh+QQFGQAAACwAAAAAAwADAIBMaXEAAP8CA4x/BQA7",
    },
    delivery: "inline",
  },
  "barcode-generator": {
    options: { text: "ABC123", format: "CODE128" },
    format: "png",
  },
  "barcode-reader": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAlsAAAHvCAAAAABGHUVTAAAFLElEQVR4nO3UMQ6DMBAAwZD//9mpSGMh2YRVmpkKAYeNWHGM18OO82AsnPmat7F1z9b4fGk2bi2xMn4sTM1L3Hvg1n5WXnnL+7dxuKQtKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qKiLSraoqItKtqioi0q2qJyjMefeB6M6zP8y8rXeep7+W9R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RYVbVHRFhVtUdEWFW1R0RavyAdcvBvbaVie9wAAAABJRU5ErkJggg==",
  },
  "curl-converter": {
    input: "curl https://example.com",
    target: "javascript-fetch",
  },
  "png-optimizer": {
    source: {
      input:
        "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADklEQVQImWP4DwYMEAoAU7oL9W/sIDEAAAAASUVORK5CYII=",
    },
    delivery: "inline",
  },
  "svg-optimizer": {
    source: {
      input:
        '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>',
    },
    delivery: "inline",
  },
  "pgp-key-generator": {
    name: "Public example",
    email: "example@example.com",
    algorithm: "ecc",
  },
  "qr-code-generator": {
    content: { type: "text", text: "Public QR example" },
    format: "png",
  },
  "qr-code-reader": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAN4AAADeAQAAAAB6HIMaAAABS0lEQVR42u1YwY3EMBAanQtwSW7dJbkAS7MD2PndfZeTYuVhZT6IZYBs5O9nxzt8h77DwBktZ/SZK+qp02r4E3+cbwyBtoDlGgU1eu6ebQ29NEW7ohBu0HuR8+6Mtriti7j1R1uUguFuzy1//R0gFvvlrdvjCet5rD1BpxwsYWKkWvbmqlvKYJYSNpVQd1tuAbLMNrBc8DFvJZBSbNlJByxdpDHaR7eNyZu4+3pCyrUW6BV+ZwcDsQgIEPuksK0noHd12deEho09oVTKekDFLlVHYyXQvtQWrtka++3xrinRNlKd3q1GiZZqOMZoQWlOBlmQYYSabzrE0HIx0Ybem3cw5YKE0Yw7mPqtKq46WDNO3vvNm1udnJ6W5t9lNyb4sRPmaNXB6L1TDLujPU47nTtYu4kQd8WcdXs8oU8ab7Ak+KJ9/7p8h/9t+AFDCyADLB/cnAAAAABJRU5ErkJggg==",
  },
  "csr-generator": {
    algorithm: "ecdsa",
    ecCurve: "P-256",
    subject: { commonName: "example.com" },
  },
  "certificate-public-key-parser": {
    text: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExncmTI8KdyV+h30wtfmfQAEfKhPY\nH7CJKBDn/UWhUi0csMB8vGP1Vt5x63BjV9hwH69YIknDhn/o2LcUPiWjoA==\n-----END PUBLIC KEY-----\n",
  },
  "image-to-avif-converter": {
    inputs: [
      {
        input:
          "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADklEQVQImWP4DwYMEAoAU7oL9W/sIDEAAAAASUVORK5CYII=",
      },
    ],
    delivery: "inline",
  },
  "image-to-ico": {
    source: {
      input:
        "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADklEQVQImWP4DwYMEAoAU7oL9W/sIDEAAAAASUVORK5CYII=",
    },
    options: { sizes: [16, 32] },
    delivery: "inline",
  },
  "ssh-key-generator": { algorithm: "ed25519", comment: "public-example" },
  "ssh-public-key-fingerprint": {
    text: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFwI2xJ9pdVkeOK3FKKD49hKrKuqbRwTU6e8Q/5RhWHX public-example",
  },
  "jwt-decoder-verifier": {
    token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwdWJsaWMtc2FtcGxlIn0.c2FtcGxl",
    action: "decode",
  },
  "jwt-signer": {
    payload: '{"sub":"public-sample"}',
    key: "public-example-key-not-for-production",
    keyFormat: "secret",
    algorithm: "HS256",
  },
  "jwk-pem-converter": {
    mode: "jwkToPem",
    input:
      '{"kty":"EC","x":"oAi1u45JIS6moAylh7Ng6rZNt1z0Lil72nvNi4PfCjw","y":"9iSBheeJ71--Qkw9Yz7OiP0TzvIbO3MQCgioBQcnHhg","crv":"P-256"}',
    outputType: "public",
  },
  "prettier-code-formatter": {
    input: "const sample={value:1};",
    options: { language: "javascript" },
  },
  "sql-formatter-and-linter": {
    input: "select id from items;",
    options: { dialect: "sql", keywordCase: "upper" },
  },
  "image-to-pdf-converter": {
    inputs: [
      {
        input:
          "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADklEQVQImWP4DwYMEAoAU7oL9W/sIDEAAAAASUVORK5CYII=",
      },
    ],
    delivery: "inline",
  },
  "remove-pdf-owner-password": {
    source: { input: publicPdfExample },
    delivery: "inline",
  },
  "cityhash64-hash-text-or-file": { text: "abc", seed: "" },
  "highwayhash-hash-text-or-file": {
    text: "abc",
    key: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
    outputSize: 256,
  },
  "robots-txt-generator": {
    state: {
      groups: [
        {
          userAgents: ["*"],
          rules: [{ type: "disallow", path: "/admin/" }],
          crawlDelay: null,
        },
      ],
      sitemaps: [],
      host: "",
      advanced: false,
    },
  },
  "sitemap-xml-generator": {
    state: {
      mode: "urlset",
      baseUrl: "https://example.com",
      autoJoin: true,
      urlEntries: [
        { loc: "/", lastmod: "", changefreq: "daily", priority: "1.0" },
      ],
      sitemapEntries: [],
    },
  },
  "pdf-info-viewer": { source: { input: publicPdfExample } },
  "pdf-text-extractor": {
    source: { input: publicPdfExample },
    outputFormat: "json",
  },
  "pdf-to-image-converter": {
    source: { input: publicPdfExample },
    pages: "1",
    dpi: 72,
    format: "png",
    delivery: "inline",
  },
  "siphash-2-4-hash-text-or-file": {
    text: "abc",
    key: "000102030405060708090a0b0c0d0e0f",
  },
  "siphash-128-2-4-hash-text-or-file": {
    text: "abc",
    key: "000102030405060708090a0b0c0d0e0f",
  },

  "ripemd128-hash-text-or-file": { text: "abc" },
  "ripemd256-hash-text-or-file": { text: "abc" },
  "ripemd320-hash-text-or-file": { text: "abc" },

  "pdf-merger": {
    inputs: [{ input: publicPdfExample }, { input: publicPdfExample }],
    delivery: "inline",
  },
  "pdf-splitter": {
    source: { input: publicPdfExample },
    ranges: "1",
    delivery: "inline",
  },
  "pdf-page-organizer": {
    source: { input: publicPdfExample },
    plan: [
      { page: 2, rotation: 90 },
      { page: 1, rotation: 0 },
    ],
    delivery: "inline",
  },
  "pdf-page-number-adder": {
    source: { input: publicPdfExample },
    delivery: "inline",
  },
  "markdown-previewer": { input: "# ToolTab\n\nLocal tools." },
  "markdown-to-html-converter": { input: "# ToolTab\n\nLocal tools." },
  "html-to-markdown-converter": {
    input: "<h1>ToolTab</h1><p>Local tools.</p>",
  },
  "murmurhash3-x86-32-hash-text-or-file": { text: "abc", seed: "4294967295" },
  "murmurhash3-x86-128-hash-text-or-file": { text: "abc", seed: "4294967295" },
  "murmurhash3-x64-128-hash-text-or-file": { text: "abc", seed: "4294967295" },

  "crc-checksum-calculator": { text: "123456789", filter: "all" },
  "exif-viewer": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC",
  },
  "image-metadata-cleaner": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC",
  },
  "xxhash-xxh32-hash-text-or-file": { text: "abc" },
  "xxhash-xxh64-hash-text-or-file": { text: "abc" },
  "xxhash-xxh3-64-hash-text-or-file": {
    text: "abc",
    seed: "18446744073709551615",
  },
  "xxhash-xxh3-128-hash-text-or-file": {
    text: "abc",
    seed: "18446744073709551615",
  },

  "json-diff-path": { input: "[0,1,2]", modified: "[]", mode: "patch" },
  "json-schema-generator": { input: '{"name":"ToolTab","items":[1,2]}' },
  "json-schema-validator": {
    input: '{"name":"ToolTab"}',
    schema: '{"type":"object","required":["name"]}',
  },
  "md4-hash-text-or-file": { text: "abc" },
  "sm3-hash-text-or-file": { text: "abc" },
  "whirlpool-hash-text-or-file": { text: "abc" },
  "aes-encryptor": {
    input: "ToolTab public sample",
    keySource: "raw",
    rawKeyHex: "00000000000000000000000000000000",
    keyLengthBits: 128,
  },
  "aes-decryptor": {
    input:
      '{\n  "version": "inbrowser-aes-v1",\n  "algorithm": "AES-GCM",\n  "key": {\n    "source": "raw",\n    "lengthBits": 128\n  },\n  "iv": "9e586c5c3441f6f7796085c8",\n  "ciphertext": "czTp2dKVJ7Z15Ev44h1tiYYWBja/z4qi5ZvUHxHOSxstn9SE7A==",\n  "encoding": "base64",\n  "plaintext": {\n    "type": "text"\n  }\n}\n',
    rawKeyHex: "00000000000000000000000000000000",
  },
  "email-validator": { input: "sample@example.com" },
  "eu-vat-number-validator": { input: "DE136695976" },
  "prc-id-validator": { input: "11010519491231002X", today: "2026-01-01" },
  "ksuid-generator": { count: 2, timestamp: 1700000000.5 },
  "jsonpath-tester": {
    input: '{"items":[{"n":9007199254740993},{"n":2}]}',
    query: "$.items[*].n",
  },
  "jmespath-tester": {
    input: '{"items":[{"n":9007199254740993},{"n":2}]}',
    query: "sort(items[].n)",
  },
  "bip39-mnemonic-generator": {
    mode: "entropy-to-mnemonic",
    entropy: "00000000000000000000000000000000",
    language: "english",
  },
  "pbkdf2-key-derivation": {
    password: "synthetic-password",
    salt: { text: "synthetic-salt", format: "utf-8" },
    iterations: 1,
    lengthBytes: 16,
  },
  "scrypt-key-derivation": {
    password: "synthetic-password",
    salt: { text: "synthetic-salt", format: "utf-8" },
    costFactor: 16,
    blockSize: 1,
    parallelism: 1,
    lengthBytes: 16,
  },
  "random-password-generator": { mode: "pin", length: 8 },
  "password-strength-checker": { password: "password123", locale: "en-US" },
  "argon2-hash-password": {
    password: "ToolTab synthetic sample",
    algorithm: "argon2id",
    salt: "c3ludGhldGljLXNhbHQ=",
    iterations: 1,
    memorySize: 8,
    parallelism: 1,
    hashLength: 16,
  },
  "argon2-hash-password-verifier": {
    password: "ToolTab synthetic sample",
    hash: "$argon2id$v=19$m=8,t=1,p=1$c3ludGhldGljLXNhbHQ$4G6CeXeiqX+9cxvDkgB89w",
  },

  "bcrypt-hash-password": { password: "ToolTab synthetic sample", cost: 4 },
  "bcrypt-hash-password-verifier": {
    password: "ToolTab synthetic sample",
    hash: "$2b$04$......................dUgOo5NEgMRnFiJQjTvFYc0yFWEK3pK",
  },

  "random-number-generator": {
    min: "1.234567",
    max: "1.234567",
    count: 2,
    numberType: "decimal",
    decimalPlaces: 6,
  },
  "http-status-code-lookup": { query: "404" },
  "mime-type-lookup": { query: "json", filter: "application" },
  "port-number-lookup": { query: "53", filter: "system" },
  "cron-expression-parser": {
    expression: "0 9 * * 1-5",
    reference: "2026-09-01T00:00:00Z",
    timeZone: "UTC",
    count: 3,
  },
  "cron-expression-generator": {
    form: {
      minute: {
        mode: "every",
        interval: 5,
        specificValues: [],
        rangeStart: 0,
        rangeEnd: 59,
      },
      hour: {
        mode: "every",
        interval: 5,
        specificValues: [],
        rangeStart: 0,
        rangeEnd: 23,
      },
      dayOfMonth: {
        mode: "every",
        interval: 5,
        specificValues: [],
        rangeStart: 1,
        rangeEnd: 31,
      },
      month: {
        mode: "every",
        interval: 5,
        specificValues: [],
        rangeStart: 1,
        rangeEnd: 12,
      },
      dayOfWeek: {
        mode: "every",
        interval: 5,
        specificValues: [],
        rangeStart: 0,
        rangeEnd: 7,
      },
    },
    reference: "2026-09-01T00:00:00Z",
    timeZone: "UTC",
    count: 3,
  },
  "unicode-invisible-character-checker": { input: "Tool\u200bTab" },
  "morse-code-converter": { input: "SOS", mode: "encode" },
  "lorem-ipsum-generator": { mode: "words", count: 5, locale: "en", seed: 42 },

  "json-to-xml-converter": {
    input: '{"name":"ToolTab","id":9007199254740993}',
  },
  "xml-to-json-converter": {
    input: '<project name="ToolTab"><item>1</item><item>2</item></project>',
  },
  "file-to-data-uri-converter": {
    source: { inputBase64: "VG9vbFRhYg==" },
    mimeType: "text/plain",
  },
  "data-uri-to-file-converter": {
    source: { input: "data:text/plain,ToolTab" },
    filename: "example.txt",
  },

  "html-color-names": { query: "#00FFFF", category: "cyan" },
  "time-zone-converter": {
    input: "2026-01-15T12:00:00",
    fromZone: "UTC",
    toZone: "Asia/Shanghai",
  },
  "time-diff-calculator": {
    start: "2026-01-15T12:00:00",
    startZone: "UTC",
    end: "2026-01-16T12:00:00",
    endZone: "UTC",
  },
  "duration-calculator": {
    base: "2026-01-15T12:00:00",
    timeZone: "UTC",
    duration: "PT90M",
  },
  "business-days-calculator": {
    start: "2026-01-01",
    end: "2026-01-31",
    base: "2026-01-01",
    offset: 5,
  },
  "json-to-yaml-converter": {
    input: '{"name":"ToolTab","id":9007199254740993}',
  },
  "yaml-to-json-converter": { input: "name: ToolTab\nid: 9007199254740993" },
  "json-to-toml-converter": {
    input: '{"name":"ToolTab","id":9007199254740993}',
  },
  "toml-to-json-converter": { input: 'name="ToolTab"\nid=9007199254740993' },
  "yaml-to-toml-converter": { input: "name: ToolTab\nid: 9007199254740993" },
  "toml-to-yaml-converter": { input: 'name="ToolTab"\nid=9007199254740993' },
  "text-diff": { original: "one\ntwo", modified: "one\nthree" },
  "regex-tester-replacer": {
    input: "item 42",
    pattern: "(\\d+)",
    flags: "g",
    replacement: "[$1]",
  },
  "cidr-parser": { input: "192.0.2.7/24" },
  "ip-cidr-normalizer": { input: "2001:db8::1234/64" },
  "ip-range-to-cidr-converter": { start: "192.0.2.1", end: "192.0.2.10" },
  "cidrs-merger-excluder": { merge: "192.0.2.0/24", exclude: "192.0.2.128/25" },
  "csv-to-json-converter": { input: "name,value\nAlice,12" },
  "json-to-csv-converter": { input: '[{"name":"Alice","value":12}]' },
  "mac-address-to-ipv6-link-local-address-converter": {
    input: "02:00:00:00:00:01",
  },
  "ipv6-address-to-mac-address-converter": { input: "fe80::ff:fe00:1" },
  "unicode-punycode-converter": { input: "bücher.example" },
  "url-parser-builder": {
    operation: "parse",
    input: "https://example.com/path?tag=one&tag=two",
  },
  "hmac-generator": {
    input: "Hello ToolTab",
    key: "synthetic-example-key",
    algorithm: "SHA-256",
  },
  "sri-hash-generator": { input: 'console.log("Hello ToolTab")' },
  "ulid-generator": { count: 3, monotonic: true },
  "nanoid-generator": { count: 3, length: 21, preset: "url-safe" },
  "cuid2-generator": { count: 3, length: 24 },
  "isbn-validator": { input: "0306406152" },
  "vin-validator": { input: "1G4AH59H45G118341" },
  "credit-card-validator": { input: "4111111111111111" },
  "list-comparer": { left: "apple\npear", right: "pear\nplum" },
  "slug-generator": { input: "Hello World" },
  "chmod-calculator": { input: "755", format: "numeric" },
  "css-box-shadow-generator": {
    layers: [
      {
        offsetX: 0,
        offsetY: 12,
        blur: 32,
        spread: 0,
        color: "#00000033",
        inset: false,
      },
    ],
  },
  "css-gradient-generator": {
    layers: [
      {
        type: "linear",
        angle: 135,
        centerX: 50,
        centerY: 50,
        radialShape: "circle",
        radialSize: "farthest-corner",
        colorSpace: "srgb",
        blendMode: "normal",
        stops: [
          { color: "#0ea5e9", position: 0 },
          { color: "#8b5cf6", position: 100 },
        ],
      },
    ],
    format: "hex",
    width: 320,
    height: 200,
  },
  "iban-validator": { input: "GB82 WEST 1234 5698 7654 32" },
  "bic-swift-validator": { input: "DEUTDEFF" },
  "imei-validator": { input: "490154203237518" },
  "unix-timestamp-converter": {
    mode: "timestamp",
    input: "0",
    unit: "seconds",
    zone: "UTC",
  },
  "color-converter": { input: "#ef4444", showAlpha: true },
  "color-contrast-checker": { foreground: "#000000", background: "#ffffff" },
  "svg-to-image": {
    input:
      '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect width="120" height="80" fill="#ef4444"/></svg>',
    format: "png",
    scale: 1,
  },
  "placeholder-generator": {
    width: 320,
    height: 200,
    text: "ToolTab",
    format: "png",
  },
  "adler32-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "md5-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "ripemd160-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },

  "html-entity-encoder-decoder": {
    input: "<ToolTab> & ",
    direction: "encode",
    format: "named",
    range: "minimal",
  },
  "unicode-escape-unescape": {
    input: "工具",
    direction: "escape",
    format: "utf16",
  },
  "rot-cipher": { input: "Hello ToolTab 123", type: 13 },
  "base58-encoder": {
    input: "Hello World",
    encoding: "utf8",
    alphabet: "bitcoin",
  },
  "base58-decoder": {
    input: "JxF12TrwUP45BMd",
    outputEncoding: "utf8",
    alphabet: "bitcoin",
  },
  "base85-encoder": { input: "test", encoding: "utf8", variant: "z85" },
  "base85-decoder": { input: "By/Jn", outputEncoding: "utf8", variant: "z85" },
  "palette-extractor": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC",
    count: 6,
    format: "css",
  },
  "number-base-converter": { input: "9007199254740993", from: 10, to: 16 },
  "roman-numeral-converter": { input: "2026", direction: "toRoman" },
  "chinese-uppercase-number-converter": {
    input: "1234.56",
    direction: "toChinese",
    traditional: false,
  },
  "basic-auth-generator": {
    username: "sample-user",
    password: "sample-password",
    encoding: "utf8",
  },
  "basic-auth-decoder": {
    input: "Basic c2FtcGxlLXVzZXI6c2FtcGxlLXBhc3N3b3Jk",
    encoding: "utf8",
  },
  "cookie-parser": { input: "theme=light; sample=value", type: "cookie" },
  "base16-encoder": { input: "foo", encoding: "utf8" },
  "base16-decoder": { input: "666F6F", outputEncoding: "utf8" },
  "base32-encoder": { input: "foo", encoding: "utf8", padding: true },
  "base32-decoder": { input: "MZXW6===", outputEncoding: "utf8" },
  "uuid-v1-generator": { count: 1 },
  "uuid-v6-generator": { count: 1 },
  "uuid-v1-v6-converter": {
    input: "c232ab00-9414-11ec-b3c8-9f6bdeced846",
    from: 1,
  },
  "blake2b-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 512,
  },
  "blake2s-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 256,
  },
  "blake3-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 256,
  },
  "keccak-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 256,
  },
  "uuid-v3-generator": {
    namespace: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    name: "www.widgets.com",
  },
  "uuid-v5-generator": {
    namespace: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    name: "www.widgets.com",
  },

  "uuid-validator": { input: "01900000-0000-7000-8000-000000000001" },
  "uuid-decoder": { input: "01900000-0000-7000-8000-000000000001" },
  "uuid-base64-hex-decimal-octal-binary-converter": {
    input: "ffffffff-ffff-ffff-ffff-ffffffffffff",
    format: "uuid",
  },
  "image-to-webp": {
    inputs: [
      {
        input:
          "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC",
      },
    ],
    output: "inline",
    quality: 85,
    percent: 100,
  },
  "image-resizer": {
    input:
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC",
    width: 64,
    height: 64,
    format: "png",
    quality: 85,
  },
  "uuid-v7-generator": { count: 1 },
  "sha224-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "sha512-224-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "sha512-256-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "sha3-224-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "sha3-256-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "sha3-384-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "sha3-512-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
  },
  "shake128-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 256,
  },
  "shake256-hash-text-or-file": {
    input: "abc",
    encoding: "utf8",
    format: "hex",
    outputBits: 512,
  },

  "sha1-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "sha256-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "sha384-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "sha512-hash-text-or-file": { input: "abc", encoding: "utf8", format: "hex" },
  "uuid-v4-generator": {},
  "uuid-v4-bulk-generator": { count: 10 },
  "uuid-nil-generator": {},
  "uuid-max-generator": {},
  "case-converter": { input: "helloWorld HTTP request" },
  "text-statistics": { input: "Hello ToolTab. Hello world!", locale: "en-US" },
  "ipv6-ula-generator": { subnetId: "0001" },
  "json-formatter": {
    input: '{"name":"ToolTab","count":9007199254740993}',
    indent: "2",
  },
  "base64-encoder-decoder": {
    input: "Hello ToolTab 你好",
    operation: "encode",
  },
  "url-component-encoder-decoder": {
    input: "Hello ToolTab 你好",
    operation: "encode",
    mode: "component",
  },
} as const;
